futureCode/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lib/', include('libary.urls')),
    path('', include('shop.urls')),
    path('basket/', include('basket.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from .views import *
urlpatterns = [
    path('product/one-filter/', get_one_filter_product, name='get_one_filter_product'),
    path('product/all/', product_list, name='product_list'),
    path('product/more-filter/', get_more_filter_product, name='get_more_filter_product'),
    path('', product_catalog_with_filter, name='product_filter_page'),
    path('product/create/', create_product, name='create_product'),
    path('product/details/<int:id>/', get_product_by_id, name='about_product'),
    path('product/review/<int:id>', UpdateRating.as_view(), name ='edit_review'),
    path('supplier/', ListSupplier.as_view(), name='supplier_list'),
    path('supplier/create/', CreateSupplier.as_view(), name='supplier_create'),
    path('supplier/detail/<int:pk>/', DetailSupplier.as_view(), name='supplier_detail'),
    path('supplier/update/<int:pk>', UpdateSupplier.as_view(), name = 'supplier_update'),
    path('supplier/delete/<int:pk>', DeleteSupplier.as_view(), name = 'supplier_delete'),
    path('warehouse/add/', AddWarehouse.as_view(), name='add_warehouse'),
    path('order/<int:pk>/', OrderDetail.as_view(), name='order_detail'),
    path('product/more/<int:id>/', get_one_product, name='get_one_product'),
]

shop/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.urls import reverse_lazy
from .utils import sum_price_count
from django.contrib.auth.models import User

# Create your models here.
MAX_LENGTH_CHAR = 255

class Supplier(models.Model):
    name = models.CharField(max_length=MAX_LENGTH_CHAR, unique=True, verbose_name='Название компании')
    agent_lastname = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Фамилия представителя')
    agent_name = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Имя представителя')
    agent_surname = models.CharField(max_length=MAX_LENGTH_CHAR, null=True, blank=True, verbose_name='Отчество представителя')
    agent_telephone = models.CharField(max_length=16, verbose_name='Телефон представителя')
    address = models.CharField(max_length=MAX_LENGTH_CHAR,verbose_name='Адрес')
    is_exists = models.BooleanField(default=True, verbose_name='Логическое удаление')

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse_lazy('supplier_detail', kwargs={'pk':self.pk})

    class Meta:
        verbose_name = 'Поставщика'
        verbose_name_plural = 'Поставщики'

class Supply(models.Model):
    data_supply = models.DateTimeField(verbose_name="Дата поставки товара")
    supplier = models.ForeignKey("Supplier", on_delete=models.PROTECT, verbose_name='Поставщик')
    product = models.ManyToManyField('Product', through='Pos_supply', verbose_name='Товар')

    def __str__(self):
        return f"Номер №{self.pk} - {self.data_supply}"
    
    class Meta:
        verbose_name = 'Поставка'
        verbose_name_plural = 'Поставки'


class Parametr(models.Model):
    name = models.CharField(max_length=MAX_LENGTH_CHAR, unique=True, verbose_name='Название')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Характеристика'
        verbose_name_plural = 'Характеристики'

class Tag(models.Model):
    name = models.CharField(max_length=MAX_LENGTH_CHAR, unique=True, verbose_name='Название')
    description = models.CharField(max_length=MAX_LENGTH_CHAR, blank=True, null=True, verbose_name='Описание')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Тег'
        verbose_name_plural = 'Теги'

class Category(models.Model):
    name = models.CharField(max_length=MAX_LENGTH_CHAR, unique=True, verbose_name='Название')
    description = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Описание')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Order(models.Model):
    SHOP = "SH"
    COURIER = "CR"
    PICKUPPOINT = "PP"
    TYPE_DELIVERY = [
        (SHOP, 'Магазин'),
        (COURIER, 'Доставка курьером'),
        (PICKUPPOINT, 'Пункт выдачи')

    ]
    user = models.ForeignKey( User, on_delete=models.PROTECT, verbose_name='Пользователь', null=False, blank=False)
    buyer_lastname = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Фамилия покупателя')
    buyer_name = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Имя покупателя')
    buyer_surname = models.CharField(max_length=MAX_LENGTH_CHAR, blank=True, null=True, verbose_name='Отчество покупателя')
    comment = models.CharField(max_length=MAX_LENGTH_CHAR, blank=True, null=True, verbose_name='Комментарий к заказу')
    delivery_address = models.CharField(max_length=MAX_LENGTH_CHAR, blank=True, null=True, verbose_name='Адрес доставки')
    delivery_type = models.CharField(max_length=2, choices=TYPE_DELIVERY, default=SHOP, verbose_name='Способ доставки')
    date_create = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    date_finish = models.DateTimeField(null=True, blank=True, verbose_name='Дата завершения')
    is_packed = models.BooleanField(default=False, verbose_name='Товар упакован')
    is_ready = models.BooleanField(default=False, verbose_name='Товар готов к получению')

    product = models.ManyToManyField('Product', through='Pos_order', verbose_name='Товар')

    def __str__(self):
        return f'{self.pk} - ({self.buyer_lastname} {self.buyer_name}) {self.date_create}'


    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'



class Product(models.Model):
    name = models.CharField(max_length=MAX_LENGTH_CHAR, unique=True, verbose_name='Название')
    description = models.TextField(blank=True, null=True, verbose_name='Описание')
    price = models.FloatField(verbose_name='Цена')
    create_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')
    update_date = models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')
    photo = models.ImageField(upload_to='image/%Y/%m/%d', null=True, blank=True, verbose_name='Фотография товара')
    is_exists = models.BooleanField(default=True, verbose_name='Логическое удаление')

    parametr = models.ManyToManyField(Parametr, through='Pos_parametr', verbose_name='Характеристики товара', default='Без параметра')
    category = models.ForeignKey(Category,on_delete=models.PROTECT, verbose_name='Категория')
    tag = models.ManyToManyField(Tag, blank=True, verbose_name='Тег', default='Без тега')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'



class Pos_parametr(models.Model):
    product = models.ForeignKey(Product, on_delete=models.PROTECT, verbose_name='Товар')
    parametr = models.ForeignKey(Parametr, on_delete=models.PROTECT, verbose_name='Характеристика')
    value = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Значение')

    def __str__(self):
        return f'{self.product.name} - {self.value}'

    class Meta:
        verbose_name = 'Характеристика товара'
        verbose_name_plural = 'Характеристики товаров'

class Pos_order(models.Model):
    product = models.ForeignKey(Product, on_delete=models.PROTECT, verbose_name='Товар')
    order = models.ForeignKey(Order, on_delete=models.PROTECT, verbose_name='Заказ')
    count = models.PositiveIntegerField(default=1, verbose_name='Количество товара')
    discount = models.PositiveIntegerField(default=0, verbose_name='Скидка')

    def __str__(self):
        return f'{self.order.pk} {self.product.name} - {self.order.buyer_lastname}'
    
    def sum_price_count(self):
        return sum_price_count(price=self.product.price, count = self.count, discount=self.discount)

    class Meta:
        verbose_name = 'Позиция заказа'
        verbose_name_plural = 'Позиции заказов'


class Pos_supply(models.Model):
    product = models.ForeignKey('Product', on_delete=models.PROTECT, verbose_name='Продукт')
    supply = models.ForeignKey('Supply', on_delete = models.PROTECT, verbose_name='Поставка')
    count = models.PositiveIntegerField(verbose_name='Количество товара')
    
    def __str__(self):
        return f"Товар: {self.product}, Номер поствки: {self.supply}, Количество товара: {self.count}"
    
    class Meta:
        verbose_name = 'Позиция поставки'
        verbose_name_plural = 'Позиции поставок'



class Manufacturer(models.Model):
    name = models.CharField(max_length=MAX_LENGTH_CHAR, unique=True, verbose_name='Производитель')
    country = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Страна')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Производитель'
        verbose_name_plural = 'Производители'


class Warehouse(models.Model):
    location = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Местоположение')
    capacity = models.PositiveIntegerField(verbose_name='Вместимость')

    def __str__(self):
        return self.location

    class Meta:
        verbose_name = 'Склад'
        verbose_name_plural = 'Склады'


class Inventory(models.Model):
    product = models.ForeignKey(Product, on_delete=models.PROTECT, verbose_name='Товар')
    warehouse = models.ForeignKey(Warehouse, on_delete=models.PROTECT, verbose_name='Склад')
    quantity = models.PositiveIntegerField(verbose_name='Количество')

    def __str__(self):
        return f'{self.product.name} - {self.warehouse.location}'

    class Meta:
        verbose_name = 'Инвентарь'
        verbose_name_plural = 'Инвентарь'


class Review(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Товар')
    user = models.ForeignKey(User, on_delete = models.CASCADE, verbose_name='Пользователь', related_name='reviews')
    rating = models.PositiveIntegerField(verbose_name='Рейтинг', validators=[MinValueValidator(1), MaxValueValidator(5)])
    comment = models.TextField(verbose_name='Комментарий')

    def __str__(self):
        return f'{self.user.username} - {self.product.name}'

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'
        unique_together = ('product', 'user')


class Discount(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Товар')
    percentage = models.PositiveIntegerField(verbose_name='Процент скидки')
    start_date = models.DateField(verbose_name='Дата начала')
    end_date = models.DateField(verbose_name='Дата окончания')

    def __str__(self):
        return f'{self.product.name} - {self.percentage}%'

    class Meta:
        verbose_name = 'Скидка'
        verbose_name_plural = 'Скидки'


class Shipment(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, verbose_name='Заказ')
    date_shipped = models.DateTimeField(verbose_name='Дата отправки')
    tracking_number = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Номер отслеживания')

    def __str__(self):
        return f'{self.order.pk} - {self.tracking_number}'

    class Meta:
        verbose_name = 'Отправка'
        verbose_name_plural = 'Отправки'

shop/forms.py
from django import forms
import re
from .models import *
from django.core.exceptions import ValidationError

class ProductCreationForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = (
            'name',
            'description',
            'price',
            'photo',
            'parametr',
            'category',
            'tag'
        )

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'price': forms.NumberInput(attrs={'class': 'form-control'}),
            'photo': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'parametr': forms.SelectMultiple(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'form-control'}),
            'tag': forms.SelectMultiple(attrs={'class': 'form-control'}),
        }

    parametr = forms.ModelMultipleChoiceField(
        queryset=Parametr.objects.all(),
        widget=forms.SelectMultiple(attrs={'class': 'form-control'})
    )

    category = forms.ModelChoiceField(
        queryset=Category.objects.all(),
        widget=forms.Select(attrs={'class': 'form-control'})
    )

    tag = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.SelectMultiple(attrs={'class': 'form-control'})
    )


class ProductFilterForm(forms.Form):
    name = forms.CharField(
        label='Название товара',
        required=False,
        min_length=2,
        max_length=150,
        strip=True,
        widget=forms.TextInput(
            attrs={'class': 'form-control'}
        )
    )
    min_price = forms.DecimalField(
        label='Минимальная цена',
        required=False,
        min_value=0,
        decimal_places=2,
        max_digits=10,
        widget=forms.NumberInput(
            attrs={'class': 'form-control'}
        )
    )
    max_price = forms.DecimalField(
        label='Максимальная цена',
        required=False,
        min_value=1,
        decimal_places=2,
        max_digits=10,
        widget=forms.NumberInput(
            attrs={'class': 'form-control'}
        )

   )

class FeebBack(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('rating', 'comment')

        widgets = {
            'rating': forms.NumberInput(attrs={'class':'form-control'}),
            'comment': forms.Textarea(attrs={'class':'form-control'})
        }


class SupplierForm(forms.ModelForm):
    class Meta:
        model = Supplier
        fields = ('name', 'agent_lastname', 'agent_name', 'agent_surname', 'agent_telephone', 'address', 'is_exists')

        widgets = {
            'name': forms.TextInput(attrs={'class':'form-control'}),
            'agent_lastname': forms.TextInput(attrs={'class': 'form-control'}),
            'agent_name': forms.TextInput(attrs={'class':'form-control'}),
            'agent_surname': forms.TextInput(attrs={'class':'form-control'}),
            'agent_telephone': forms.TextInput(attrs={'class':'form-control'}),
            'address': forms.TextInput(attrs={'class':'form-control'}),
            'is_exists':forms.CheckboxInput(attrs={'class':'form-control'})
        }

class AddWarehouseForm(forms.ModelForm):
    class Meta:
        model = Warehouse
        fields = ('location','capacity')

        widgets = {
            'location': forms.TextInput(attrs={'class':'form-contol'}),
            'capacity': forms.NumberInput(attrs={'class':'form-control'})
        }

class AddOrder(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('buyer_lastname', 'buyer_name', 'buyer_surname', 'comment', 'delivery_address', 'delivery_type', 'date_finish', 'product')

        widgets = {
            'buyer_lastname': forms.TextInput(attrs={'class': 'form-control'}),
            'buyer_name': forms.TextInput(attrs={'class': 'form-control'}),
            'buyer_surname': forms.TextInput(attrs={'class':'form-control'}),
            'comment': forms.Textarea(attrs={'class': 'form-contorl'}),
            'delivery_address': forms.TextInput(attrs={'class': 'form-contorl'}),
            'delivery_type': forms.Select(attrs={'class': 'form-contorl'}),
            'date_finish': forms.DateTimeInput(attrs={'class': 'form-control', 'type': 'datetime-local'}),
            'product': forms.SelectMultiple(attrs={'class': 'form-control'})
        }
    
    product = forms.ModelMultipleChoiceField(
        queryset=Product.objects.all(),
        widget=forms.SelectMultiple(attrs={'class':'form-control'}),
        required = False
    )

''' class Return(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, verbose_name='Заказ')
    reason = models.TextField(verbose_name='Причина возврата')
    date_returned = models.DateTimeField(verbose_name='Дата возврата')

    def __str__(self):
        return f'{self.order.pk} - {self.date_returned}'

    class Meta:
        verbose_name = 'Возврат'
        verbose_name_plural = 'Возвраты'
'''

class ReturnProductForm(forms.ModelForm):
    class Meta:
        model = Return
        fields = ('order', 'reason', 'date_returned')

        widgets = {
            'order': forms.Select(),
            'reason': forms.Textarea(attrs={'class':'form-control'}),
            'date_returned': forms.DateTimeInput(attrs={'type': 'datetime-local'})
        }

shop/templates/shop/product/catalog.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Список заказов</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body class="bg-light">
    <div class="container mt-5">
        <h1 class="text-center mb-4">Список заказов</h1>
        <div class="row">
            {% for order in order_list %}
                <div class="col-md-6 col-lg-4 mb-4">
                    <div class="card shadow-sm h-100">
                        <div class="card-body">
                            <h5 class="card-title">Заказ №{{ order.pk }}</h5>
                            <p class="text-muted small">Дата создания: {{ order.date_create }}</p>
                            <p><strong>Покупатель:</strong> {{ order.buyer_lastname }} {{ order.buyer_name }}</p>
                            <p><strong>Адрес доставки:</strong> {{ order.delivery_address|default:"Не указан" }}</p>
                            <p><strong>Способ доставки:</strong> {{ order.get_delivery_type_display }}</p>
                            <p><strong>Комментарий:</strong> {{ order.comment|default:"Нет комментария" }}</p>
                            <p><strong>Статус:</strong> 
                                {% if order.is_packed %} Упакован {% else %} Не упакован {% endif %}, 
                                {% if order.is_ready %} Готов к получению {% else %} В процессе {% endif %}</p>
                            
                            <h6>Товары в заказе:</h6>
                            <ul>
                                {% for product in order.product.all %}
                                    <li>{{ product.name }} - {{ product.price }} ₽</li>
                                {% empty %}
                                    <li>Нет товаров</li>
                                {% endfor %}
                            </ul>
                            
                            <a href="{% url 'product_filter_page' %}" class="btn btn-primary">Домой</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

shop/templates/shop/product/catalog_with_filter.html
{% extends 'base.html' %}
{% load static %}
{% load custom_tags %}
{% load custom_filters %}

{% block title_name %}
    Каталог с фильтрами
{% endblock %}

{% block link_additional %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <style>
        body {
            background-color: #f8f9fa;
            padding-top: 20px;
        }

        .container {
            background-color: white;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }

        .active-button {
            font-weight: bold;
            color: #007bff;
        }

        .product-card {
            border: 1px solid #dee2e6;
            border-radius: 8px;
            padding: 15px;
            margin-bottom: 20px;
            transition: transform 0.3s, box-shadow 0.3s;
            background-color: #ffffff;
            text-align: center;
        }

        .product-card:hover {
            transform: translateY(-5px);
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
        }

        .product-card img {
            width: 100%; /* Заполняет всю ширину карточки */
            height: 200px; /* Фиксированная высота */
            object-fit: contain; /* Показывает всё изображение с пропорциями */
            border-radius: 8px;
        }

        .product-card h1 {
            font-size: 20px;
            margin-top: 10px;
            margin-bottom: 10px;
        }

        .product-card p {
            margin-bottom: 10px;
        }

        .toast-container {
            position: fixed;
            top: 20px;
            right: 20px;
            z-index: 1055;
        }

        .toast {
            opacity: 0.9;
            transition: opacity 0.3s ease-in-out;
        }

        .toast .btn-close {
            background-color: transparent;
            border: none;
            color: #000;
            font-size: 1rem;
            opacity: 0.8;
            cursor: pointer;
        }

        /* Стили для кнопки и боковой панели с фильтрами */
        .filter-button {
            margin-bottom: 20px;
        }

        .filter-panel {
            position: fixed;
            top: 0;
            right: -300px;
            width: 300px;
            height: 100%;
            background-color: white;
            box-shadow: -2px 0 4px rgba(0, 0, 0, 0.1);
            padding: 20px;
            overflow-y: auto;
            z-index: 1050;
            transition: right 0.3s ease-in-out;
        }

        .filter-panel.open {
            right: 0;
        }

        .filter-panel .close-button {
            position: absolute;
            top: 10px;
            right: 10px;
            font-size: 20px;
            cursor: pointer;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="toast-container">
        {% if messages %}
            {% for message in messages %}
                <div class="toast alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    <span>{{ message }}</span>
                    <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
                </div>
            {% endfor %}
        {% endif %}
    </div>

    <div class="container">
        <!-- Кнопка для открытия фильтров -->
        <button class="btn btn-info filter-button" id="filterToggle">
            <i class="fas fa-filter"></i> Фильтры
        </button>

        <!-- Панель с фильтрами -->
        <div class="filter-panel" id="filterPanel">
            <span class="close-button" id="closeFilterPanel">&times;</span>
            <form method="get">
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary mt-3">
                    <i class="fas fa-check"></i> Применить фильтры
                </button>
            </form>
        </div>

        <!-- Список продуктов -->
        <div class="row">
            {% for product in product_list %}
                <div class="col-md-4">
                    <a href="{% url 'about_product' product.id %}" class="text-decoration-none text-dark">
                        <div class="product-card">
                            {% if product.photo %}
                                <img src="{{ product.photo.url }}" class="card-img-top" alt="{{ product.name }}">
                            {% else %}
                                <img src="{% static 'shop/images/no_photo.jpg' %}" class="card-img-top" alt="No Photo Available">
                            {% endif %}
                            <h1>{{ product.name }}</h1>
                            <p>Цена: {{ product.price|currency:"руб." }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

    <script>
        // Скрипт для открытия/закрытия панели с фильтрами
        document.addEventListener('DOMContentLoaded', function () {
            const filterToggle = document.getElementById('filterToggle');
            const filterPanel = document.getElementById('filterPanel');
            const closeFilterPanel = document.getElementById('closeFilterPanel');

            filterToggle.addEventListener('click', () => {
                filterPanel.classList.add('open');
            });

            closeFilterPanel.addEventListener('click', () => {
                filterPanel.classList.remove('open');
            });

            // Автоматическое скрытие сообщений через 5 секунд
            const toasts = document.querySelectorAll('.toast');
            toasts.forEach((toast) => {
                setTimeout(() => {
                    toast.style.opacity = '0';
                    setTimeout(() => toast.remove(), 300); // Удалить элемент после анимации
                }, 5000);
            });
        });
    </script>
{% endblock %}

shop/templates/shop/product/create_product.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Создание продукта</title>
</head>
<body>
    <h1>Создание продукта</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Создание продукта</button>
    </form>
</body>
</html>

shop/templates/shop/product/product_by_id.html
{% extends 'base.html' %}
{% load static %}

{% block title_name %}
    {{ product.name }}
{% endblock %}

{% block link_additional %}
    <link rel="stylesheet" href="{% static 'shop/css/bootstrap.css' %}">
    <style>
        body {
            background-color: #f8f9fa;
            padding-top: 20px;
        }

        .container {
            background-color: white;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }

        .product-photo {
            max-width: 100%;
            height: auto;
            border-radius: 8px;
        }

        .product-section {
            border: 1px solid #dee2e6;
            border-radius: 8px;
            padding: 15px;
            margin-bottom: 20px;
        }

        .product-params, .product-tags {
            list-style-type: none;
            padding: 0;
        }

        .product-params li, .product-tags li {
            background-color: #e9ecef;
            border-radius: 5px;
            padding: 5px;
            margin-bottom: 5px;
            display: inline-block;
        }

        .review-section {
            margin-top: 40px;
        }

        .review-form {
            margin-top: 20px;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                {% if product.photo %}
                    <img src="{{ product.photo.url }}" class="product-photo" alt="{{ product.name }}">
                {% else %}
                    <img src="{% static 'shop/images/no_photo.jpg' %}" class="product-photo" alt="No Photo Available">
                {% endif %}
            </div>
            <div class="col-md-8">
                <div class="product-section">
                    <h1>{{ product.name }}</h1>
                    <p>Категория: {{ product.category }}</p>
                    <p>{{ product.description }}</p>
                    <p>Цена: {{ product.price }} руб.</p>
                </div>

                <div class="product-section">
                    <p>Дата добавления: {{ product.create_date|date:"d.m.Y H:i" }}</p>
                    <p>Дата последнего изменения: {{ product.update_date|date:"d.m.Y H:i" }}</p>
                </div>

                <div class="product-section">
                    <h5>Характеристики:</h5>
                    <ul class="product-params">
                        {% for param in product.parametr.all %}
                            <li>{{ param.name }}</li>
                        {% endfor %}
                    </ul>
                </div>

                <div class="product-section">
                    <h5>Теги:</h5>
                    <ul class="product-tags">
                        {% for tag in product.tag.all %}
                            <li>{{ tag.name }}</li>
                        {% endfor %}
                    </ul>
                </div>

                <div class="product-section">
                    <a href="{% url 'get_one_product' product.id %}" class="btn btn-success btn-lg">
                        Купить за {{ product.price }} руб.
                    </a>
                </div>

                <div class="review-section">
                    <h3>Отзывы:</h3>
                    <ul>
                        {% for review in product.review_set.all %}
                            <li><strong>{{ review.user.username }}</strong>: {{ review.comment }} ({{ review.rating }} звёзд)</li>
                        {% empty %}
                            <li>Нет отзывов</li>
                        {% endfor %}
                    </ul>
                    <div class="review-form">
                        <h4>Оставить отзыв:</h4>
                        <form method="post">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">Отправить отзыв</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}